apiVersion: apps/v1
kind: Deployment
metadata:
  name: api 
spec: 
  replicas: 10
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      # Configurar metricas com o Prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
      labels: 
        app: api
    spec:
      containers:
        - name: api
          image: raphael3130/api-produto
          ports:
          - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb:mongouser:mongopwd@mongo-service:27017